all:
	make clean
	xelatex -interaction=nonstopmode hw02a.tex
	xelatex -interaction=nonstopmode hw02a.tex
	#bibtex hw02a.tex
	#xelatex hw02a.tex
	open hw02a.pdf
	#latex hw01a.tex
	#pdflatex hw01a.tex
clean:
	rm *.aux *.pdf *.log *.out
